### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by yeeterlol** [pigeonburger/every-frame-in-order-bot#1]
Traceback (most recent call last):
  File "/root/every-frame-in-order-bot/bot.py", line 39, in <module>
    total_frames = cursor.execute(f"SELECT frames FROM show WHERE ep = \"{current_ep}\"").fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by Bahromoken** [comment]
Traceback (most recent call last):
File "/root/every-frame-in-order-bot/bot.py", line 39, in
total_frames = cursor.execute(f"SELECT frames FROM show WHERE ep = "{current_ep}"").fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by yeeterlol** [comment]
still no reply :(

**Comment by 6306** [comment]
Traceback (most recent call last):
File "C:/Users/fool/Desktop/EAF/bot.py", line 39, in
total_frames = cursor.execute(f"SELECT frames FROM show WHERE ep = "{current_ep}"").fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
